# Pre-commit hooks configuration for GrindLab
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Python code formatting with black
- repo: https://github.com/psf/black
  rev: 24.1.1
  hooks:
  - id: black
    name: black (code formatter)
    language_version: python3
    types: [python]
    args: [--line-length=100]

  # Python import sorting
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort (import sorting)
    types: [python]
    args: [--profile=black, --line-length=100]

  # Python linting with flake8
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    name: flake8 (linting)
    types: [python]
    args: [--max-line-length=100, '--extend-ignore=E203,W503']

  # JSON formatting
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: pretty-format-json
    name: pretty-format-json
    types: [json]
    args: [--autofix]
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
    args: [--maxkb=5000]

  # YAML formatting
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.11.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
    types: [yaml]
